import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownToLine, ArrowRight, Check, Clipboard, Link2, LoaderCircle, Play, ShieldCheck, Sparkles, X } from 'lucide-react';
import './style.css';

const BASE = import.meta.env.BASE_URL;
const path = slug => `${BASE}${slug}`;
const page = location.pathname.startsWith(BASE) ? location.pathname.slice(BASE.length).replace(/\/$/, '') : '';
const API = import.meta.env.VITE_API_URL || (location.hostname === 'localhost' ? 'http://localhost:8000' : location.hostname.endsWith('github.io') ? 'https://savyour.blitz.cloud' : location.origin);
const nav = [['', 'Downloader'], ['supported-sites', 'Supported Sites'], ['how-it-works', 'How It Works'], ['faq', 'FAQ'], ['about', 'About']];
const platforms = [
  ['YouTube', 'Public videos & Shorts · up to 480p', '▶', 'youtube'],
  ['TikTok', 'Public videos', '♪', 'tiktok'],
  ['Instagram', 'Public Reels & video posts', '◎', 'instagram'],
  ['Facebook', 'Public video posts', 'f', 'facebook'],
  ['X', 'Public video posts', '𝕏', 'x'],
  ['Vimeo', 'Publicly accessible videos', 'v', 'vimeo'],
  ['Pinterest', 'Public video pins', 'p', 'pinterest'],
  ['Reddit', 'Public video posts', '●', 'reddit'],
];
const platformDetails = {
  youtube: {name:'YouTube', types:'public videos and Shorts', hint:'youtube.com/watch, youtube.com/shorts or youtu.be', domains:['youtube.com','youtu.be'], note:'YouTube downloads are limited to available formats at or below 480p in this version.', steps:'Open a public video or Short, copy its share link, and paste it below. Review the thumbnail and select a format up to 480p.'},
  tiktok: {name:'TikTok', types:'public video posts', hint:'tiktok.com video links', domains:['tiktok.com'], note:'Available formats vary by post. Private or restricted videos may not be accessible.', steps:'Copy the link to an individual public TikTok post, paste it below, and select an available quality.'},
  instagram: {name:'Instagram', types:'public Reels and video posts', hint:'instagram.com/reel or instagram.com/p', domains:['instagram.com'], note:'Instagram may require a source account to access some posts even when a preview is visible.', steps:'Open a public Reel or video post, copy its link, and paste it below to check available media.'},
  facebook: {name:'Facebook', types:'public video posts', hint:'facebook.com or fb.watch video links', domains:['facebook.com','fb.watch'], note:'Posts limited to friends, groups, or signed-in viewers cannot be downloaded through this public-link tool.', steps:'Copy the URL of an individual public Facebook video, paste it below, and review the preview.'},
  x: {name:'X', types:'public posts containing video', hint:'x.com or twitter.com post links', domains:['x.com','twitter.com'], note:'Posts without video or those requiring sign-in may not offer a downloadable format.', steps:'Copy the link to a public video post on X, paste it below, and choose an available format.'},
  vimeo: {name:'Vimeo', types:'publicly accessible videos', hint:'vimeo.com video links', domains:['vimeo.com'], note:'Availability depends on the video owner’s access and download settings.', steps:'Copy the direct link to an accessible Vimeo video and paste it below to check its formats.'},
  pinterest: {name:'Pinterest', types:'public video pins', hint:'pinterest.com or pin.it video pins', domains:['pinterest.com','pin.it'], note:'Image pins and private boards do not provide a downloadable video.', steps:'Copy the link to a public video pin, paste it below, and check its preview.'},
  reddit: {name:'Reddit', types:'public video posts', hint:'reddit.com post links', domains:['reddit.com'], note:'Text posts, restricted communities, and external embeds may not yield a video file.', steps:'Copy the link to an individual public Reddit video post, paste it below, and select a format.'},
};
function platformForUrl(value){try{const u=new URL(value.trim());return Object.entries(platformDetails).find(([,p])=>p.domains.some(d=>u.hostname===d||u.hostname.endsWith(`.${d}`)))?.[0]||null}catch{return null}}
const faqs = [
  ['Which platforms does Savyour support?', 'Savyour can analyze public links from YouTube, TikTok, Instagram, Facebook, X, Vimeo, Pinterest, and Reddit. Individual videos may still be unavailable because each platform controls access to its media.'],
  ['Why is YouTube limited to 480p?', 'In this setup, higher YouTube formats have not downloaded reliably. The quality picker and backend therefore limit YouTube to formats at or below 480p. Other platforms keep their best available quality.'],
  ['Why does a thumbnail show but the download fail?', 'A platform may expose video details while restricting its media streams. Private videos, login requirements, regional restrictions, expired links, or changes to a platform can also prevent downloads.'],
  ['Can I choose a video quality?', 'Yes. After Savyour analyzes a link, choose a displayed format or Best available. The quality and file type depend on what the source provides. YouTube choices are capped at 480p.'],
  ['What happens while a video is preparing?', 'The progress bar reports the current media stream as it downloads. When separate video and audio streams are available, it then shows the combining stage and progress while the file is saved to your computer.'],
  ['Do I need to sign in or install an extension?', 'The website has no Savyour sign-in or browser extension. Some source platforms require their own login and may not allow this tool to access the video.'],
  ['Which videos am I allowed to save?', 'Only save media you own or have permission to download. Respect creators, copyright, privacy, and the rules of the platform hosting the video.'],
];
function Logo(){ return <img className="brand-logo" src={path('logo.svg')} alt="Savyour" width="184" height="50"/>; }
function Header(){ return <header><a className="brand" href={path('')} aria-label="Savyour home"><Logo/></a><nav aria-label="Primary navigation">{nav.map(([slug,label])=><a className={page===slug?'active':''} href={path(slug?`${slug}/`:'')} key={slug} aria-current={page===slug?'page':undefined}>{label}</a>)}</nav></header>; }
function Footer(){return <footer><a className="brand" href={path('')}><Logo/></a><div className="footer-links">{nav.map(([slug,label])=><a key={slug} href={path(slug?`${slug}/`:'')}>{label}</a>)}{platforms.map(([name,,,slug])=><a key={slug} href={path(`platforms/${slug}/`)}>{name}</a>)}</div><small>© {new Date().getFullYear()} Savyour · Only save content you own or are authorized to download.</small></footer>;}
function PageIntro({eyebrow, title, accent, description}){return <div className="page-intro"><span className="eyebrow"><Sparkles size={14}/>{eyebrow}</span><h1>{title} <em>{accent}</em></h1><p>{description}</p></div>;}
function PlatformCards(){return <div className="platform-grid">{platforms.map(([name,description,symbol,cls])=><a href={path(`platforms/${cls}/`)} className={`platform-card ${cls}`} key={name}><span className="platform-icon">{symbol}</span><span className="platform-copy"><strong>{name}</strong><small>{description}</small><span className="supported"><Check size={14}/> Open downloader</span></span><ArrowRight className="card-arrow" size={19}/></a>)}</div>;}
function SupportedSites(){return <section className="page-section"><PageIntro eyebrow="ONE LINK. YOUR FAVORITE PLATFORMS." title="Supported video" accent="sites." description="Explore public video sources Savyour can analyze. Availability varies by platform, video, and location."/><PlatformCards/><div className="info-panel"><h2>What counts as a supported link?</h2><p>Paste the URL of an individual public video, Short, Reel, post, or video pin. Profile pages, private posts, playlists, and links that require source account access may not work. YouTube downloads are currently limited to 480p; other platforms offer their best available quality.</p><a className="button primary" href={path('supported-sites/')}><ArrowDownToLine size={18}/> Choose a Platform</a></div></section>;}
function HowItWorks(){const steps=[['01','Paste a public link','Copy the URL of an individual video on a supported platform and paste it into Savyour. The site checks the platform and fetches the video details.'],['02','Check the preview and formats','Review the thumbnail, title, creator, and available resolutions. Choose Best available or select a listed quality; YouTube is capped at 480p.'],['03','Save with live progress','Savyour downloads the available media streams, combines video and audio when required, and shows progress as the final file is saved to your computer.']];return <section className="page-section"><PageIntro eyebrow="PASTE. PREVIEW. SAVE." title="How Savyour" accent="works." description="A straightforward way to save public videos you own or have permission to download."/><div className="steps detailed">{steps.map(([n,t,d])=><article className="step" key={n}><b>{n}</b><h2>{t}</h2><p>{d}</p></article>)}</div><div className="info-panel"><h2>Before you download</h2><p>The source platform determines which media streams are accessible. A preview can load even when a download is blocked by a login requirement, regional rule, or platform change. Savyour does not bypass those restrictions. Save only media you own or are authorized to download.</p><a className="button primary" href={path('supported-sites/')}><ArrowDownToLine size={18}/> Choose a Platform</a></div></section>;}
function FAQ(){return <section className="page-section"><PageIntro eyebrow="ANSWERS, WITHOUT THE GUESSWORK." title="Frequently asked" accent="questions." description="Quick answers about supported sites, video quality, progress, and failed links."/><div className="faq-list">{faqs.map(([q,a])=><details className="faq-item" key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div><div className="info-panel"><h2>Ready to try a link?</h2><p>Open the downloader and paste a public video URL to see which formats are available.</p><a className="button primary" href={path('supported-sites/')}><ArrowDownToLine size={18}/> Choose a Platform</a></div></section>;}
function About(){return <section className="page-section"><PageIntro eyebrow="YOUR MEDIA. YOUR FLOW." title="Meet" accent="Savyour." description="A focused space for previewing and saving public video links when you have permission to keep the media."/><div className="about-grid"><article className="info-panel"><h2>What we built</h2><p>Savyour brings link analysis, thumbnails, available quality choices, and file saving into one clear workflow. The interface works on desktop and mobile browsers, with visible progress while media is prepared.</p></article><article className="info-panel"><h2>How access works</h2><p>Savyour handles public links from supported platforms. Access depends on the video and the platform. Some links cannot be downloaded because they are private, require login, are region restricted, or have changed since analysis.</p></article><article className="info-panel"><h2>Respect for creators</h2><p>Use Savyour to save your own media or content you are authorized to download. The creator and source platform retain their rights and rules. We do not claim that every public link can be saved.</p></article></div><a className="button primary about-cta" href={path('supported-sites/')}><ArrowDownToLine size={18}/> Choose a Platform</a></section>;}
function Downloader({platform}){
  const [url,setUrl]=useState(''), [result,setResult]=useState(null), [selected,setSelected]=useState('best');
  const [working,setWorking]=useState(false), [downloading,setDownloading]=useState(false), [error,setError]=useState('');
  const [progress,setProgress]=useState(null);
  const timer=useRef(null), current=useRef(0), input=useRef(null);
  async function analyze(value){
    const v=value.trim(); if(!v) return;
    if(platformForUrl(v)!==platform){setResult(null);setError(`Paste a ${platformDetails[platform].name} video link on this page. Choose the matching platform below for another link.`);return;}
    const seq=++current.current; setWorking(true); setResult(null); setError(''); setSelected('best');
    try{
      const response=await fetch(`${API}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:v})});
      const data=await response.json(); if(seq!==current.current) return;
      if(!response.ok) throw Error(data.detail || 'Could not analyze this link.');
      setResult(data);
    }catch(e){if(seq===current.current) setError(e instanceof TypeError?'The download server is unavailable. Please try again shortly.':(e.message||'Could not analyze this link.'));}
    finally{if(seq===current.current) setWorking(false);}
  }
  function onChange(v){setUrl(v);setResult(null);setError('');clearTimeout(timer.current);++current.current;setWorking(false);if(/^https:\/\/\S+\.[^\s]+/.test(v.trim())) timer.current=setTimeout(()=>analyze(v),650);}
  async function paste(){try{onChange(await navigator.clipboard.readText());input.current?.focus();}catch{setError('Clipboard access unavailable. Paste the link into the field.');}}
  async function download(){if(!url||downloading) return;if(platformForUrl(url)!==platform){setError(`Paste a ${platformDetails[platform].name} video link.`);return}setDownloading(true);setError('');setProgress({label:'Connecting to source…',percent:null});
    try{
      const ext=selected==='best'?'mp4':(result?.formats.find(f=>f.id===selected)?.ext||'mp4');
      const handle=window.showSaveFilePicker?await window.showSaveFilePicker({suggestedName:`${(result?.title||'savyour-video').replace(/[\\/:*?"<>|]/g,'').slice(0,90)}.${ext}` }):null;
      const started=await fetch(`${API}/api/download/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,format_id:selected})});
      const startData=await started.json();if(!started.ok) throw Error(startData.detail||'Could not start download.');
      while(true){await new Promise(resolve=>setTimeout(resolve,1000));const poll=await fetch(`${API}/api/download/${startData.id}`);const state=await poll.json();if(!poll.ok) throw Error(state.detail||'Download status unavailable.');if(state.status==='error') throw Error(state.detail);if(state.status==='ready') break;const amount=state.percent!=null?` ${state.percent}%`:state.bytes?` ${(state.bytes/1048576).toFixed(1)} MB`:'';setProgress({label:`${state.detail||'Downloading'}${amount}`,percent:state.percent});}
      setProgress({label:'Saving to your computer…',percent:null});const response=await fetch(`${API}/api/download/${startData.id}/file`);if(!response.ok){const data=await response.json();throw Error(data.detail||'Download failed.');}
      const total=Number(response.headers.get('content-length'))||null;let received=0;function showSaving(bytes){received+=bytes;setProgress({label:`Saving to your computer · ${(received/1048576).toFixed(1)} MB`,percent:total?Math.round(100*received/total):null,phase:'save'});}
      if(handle){const writer=await handle.createWritable();try{const reader=response.body.getReader();while(true){const {done,value}=await reader.read();if(done) break;await writer.write(value);showSaving(value.length)}await writer.close()}catch(e){await writer.abort();throw e}return;}
      const chunks=[];const reader=response.body.getReader();while(true){const {done,value}=await reader.read();if(done) break;chunks.push(value);showSaving(value.length)}
      const blob=new Blob(chunks,{type:response.headers.get('content-type')||'application/octet-stream'});const object=URL.createObjectURL(blob);const a=document.createElement('a');a.href=object;const disposition=response.headers.get('content-disposition')||'';const match=disposition.match(/filename\*=UTF-8''([^;]+)/i);a.download=match?decodeURIComponent(match[1]):'savyour-video.mp4';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(object),60000);
    }catch(e){if(e.name!=='AbortError') setError(e instanceof TypeError?'The download server is unavailable. Please try again shortly.':(e.message||'Download failed.'));}finally{setDownloading(false);setProgress(null);}
  }
  useEffect(()=>()=>clearTimeout(timer.current),[]);
  const chosen=result?.formats.find(f=>f.id===selected);
  const formatLabel=f=>`${f.height?`${f.height}p`:'Video'} · ${(f.ext||'video').toUpperCase()}${f.has_audio?' · audio':''}${f.size?` · ${(f.size/1048576).toFixed(1)} MB`:''}`;
  return <section className="hero platform-hero"><div className="eyebrow"><Sparkles size={14}/> SAVYOUR · {platformDetails[platform].name.toUpperCase()}</div><h1>Download {platformDetails[platform].name}<br/><span>Videos Easily.</span></h1><p className="lead">Paste a link to {platformDetails[platform].types} you own or have permission to save.</p>
    <form onSubmit={e=>{e.preventDefault();clearTimeout(timer.current);analyze(url)}} className="link-form"><Link2 size={21}/><input ref={input} type="url" value={url} onChange={e=>onChange(e.target.value)} placeholder="Paste video URL here..." aria-label="Video URL" required/>{url&&<button type="button" className="icon-clear" onClick={()=>onChange('')} aria-label="Clear link"><X size={18}/></button>}<span className="detect">{working?<><LoaderCircle size={16} className="spin"/> Analyzing</>:result?<><Check size={16}/> Ready</>:'PASTE A LINK'}</span></form>
    <div className="hero-actions"><button className="button ghost" onClick={paste}><Clipboard size={18}/> Paste Link</button><button className="button primary" onClick={()=>result?download():analyze(url)} disabled={!url||working||downloading}>{working||downloading?<LoaderCircle size={18} className="spin"/>:<ArrowDownToLine size={18}/>} {result?(downloading?'Preparing file...':'Download Best Quality'):(working?'Analyzing...':'Analyze Link')}</button></div>
    {progress&&<div role="status" className="download-progress"><div className="download-progress-label"><LoaderCircle size={16} className="spin"/> {progress.label}</div><progress max="100" value={progress.percent==null?undefined:progress.percent} aria-label="Download progress"/><small>{progress.percent==null?'Working…':`${progress.percent}% ${progress.phase==='save'?'saved':'of current stream'}`}</small></div>}
    {error&&<div role="alert" className="error">{error}</div>}
    {result&&<div className="result"><div className="preview">{result.thumbnail?<img src={result.thumbnail} alt={`Thumbnail for ${result.title}`} referrerPolicy="no-referrer"/>:<div className="no-image"><Play size={36}/></div>}<span className="play"><Play fill="currentColor" size={21}/></span></div><div className="result-info"><span className="pill ready"><Check size={14}/> VIDEO READY</span><h2>{result.title}</h2><p>{result.creator||'Public video'} · {result.platform||'Supported platform'}</p><label htmlFor="quality">Choose quality</label><select id="quality" value={selected} onChange={e=>setSelected(e.target.value)}><option value="best">{result.max_quality?'Best available up to 480p + audio':'Best available video + audio'}</option>{result.formats.map(f=><option key={f.id} value={f.id}>{formatLabel(f)}</option>)}</select><button className="button primary full" onClick={download} disabled={downloading}>{downloading?<LoaderCircle className="spin" size={18}/>:<ArrowDownToLine size={18}/>} {downloading?'Preparing download...':`Download ${chosen?.height?`${chosen.height}p`:result.max_quality?'up to 480p':'video'}`}</button><small>{result.max_quality?'YouTube is limited to 480p for reliable downloads.':'Best quality may require a few moments to combine video and audio.'}</small></div></div>}
    {!result&&<div className="platform-pills">{platforms.map(([name,,symbol,cls])=><a href={path(`platforms/${cls}/`)} aria-current={platform===cls?'page':undefined} key={name}><b className={`mini ${cls}`}>{symbol}</b>{name}</a>)}</div>}
    <div className="trust"><span><Sparkles size={16}/> Public links</span><i/><span><ShieldCheck size={16}/> Privacy focused</span><i/><span>∞ &nbsp; No extension</span></div>
  </section>;
}
function Home(){return <><section className="hero home-hero"><div className="eyebrow"><Sparkles size={14}/> YOUR MEDIA. YOUR FLOW.</div><h1>Download Social<br/><span>Videos Easily.</span></h1><p className="lead">Choose a platform to preview a public video and save content you own or have permission to download.</p><a className="button primary" href={path('supported-sites/')}>Explore supported platforms <ArrowRight size={18}/></a></section><section className="section sites home-sites"><div className="section-top"><span className="eyebrow">CHOOSE YOUR PLATFORM</span><h2>Made for the places<br/><em>you create.</em></h2><p>Each site has its own focused download page and guidance.</p></div><PlatformCards/></section><section className="section how"><div className="section-top"><span className="eyebrow">SIMPLE FROM START TO FINISH</span><h2>Three steps. <em>One flow.</em></h2></div><div className="steps">{[['01','Choose a platform','Open the page for your video source.'],['02','Paste and preview','Check the thumbnail and available formats.'],['03','Choose and save','Track progress as your permitted media is saved.']].map(([n,t,d])=><div className="step" key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div><div className="section-link"><a href={path('how-it-works/')}>How it works <ArrowRight size={17}/></a></div></section></>}
function PlatformPage({slug}){const detail=platformDetails[slug];return <><nav className="breadcrumbs" aria-label="Breadcrumb"><a href={path('')}>Home</a><span>›</span><a href={path('supported-sites/')}>Supported sites</a><span>›</span><span>{detail.name}</span></nav><Downloader platform={slug}/><section className="platform-explainer"><div className="info-panel"><h2>How to save a {detail.name} video</h2><p>{detail.steps}</p><h3>Which links work?</h3><p>Use an individual public video link, such as {detail.hint}. Profile pages, private posts and playlists are outside this tool’s scope.</p><h3>Quality and availability</h3><p>{detail.note} The preview and quality list show what the source makes available; a visible thumbnail does not guarantee a downloadable stream.</p><h3>Before you save</h3><p>Download only your own videos or media you have permission to keep. Respect the creator’s rights and the source platform’s rules.</p></div><div className="section-link"><a href={path('supported-sites/')}>Explore all supported sites <ArrowRight size={17}/></a></div></section></>}
function App(){const platform=page.match(/^platforms\/(youtube|tiktok|instagram|facebook|x|vimeo|pinterest|reddit)$/)?.[1];return <div className="app"><div className="aurora aurora-a"/><div className="aurora aurora-b"/><div className="orb orb-a"/><div className="orb orb-b"/><div className="site-shell"><Header/><main>{platform?<PlatformPage slug={platform}/>:page==='supported-sites'?<SupportedSites/>:page==='how-it-works'?<HowItWorks/>:page==='faq'?<FAQ/>:page==='about'?<About/>:<Home/>}</main><Footer/></div></div>;}
createRoot(document.getElementById('root')).render(<App/>);
